### ISSUE TITLE
add plugin `verdaccio-hello`

### ISSUE THREAD

**Issue by sinlov** [sinlov/docker-verdaccio-gitea-auth#1]
[https://github.com/bruceman/verdaccio-hello](https://github.com/bruceman/verdaccio-hello)

```yml
middlewares:
  hello:
    path: /hello # optional, default value is /hello
    text: ok # optional, default value is ok
```
